### PR TITLE
Add support for FreeBSD.

### PR DESCRIPTION
**Pull request by knz**
This implementation requires to mount the Linux compatibility /proc
filesystem in /compat/linux/proc. Check the FreeBSD handbook for
details.

### CODE REVIEW

**Comment by ruflin** [comment]
@knz Thanks for the contribution. Could you use `gofmt -w ...` to make sure your code adheres to the golang standard? Currently travis complains.

**Comment by knz** [comment]
@ruflin thanks for the hint. Also now there is significant shared/redundant code between sigar_linux.go and sigar_freebsd.go. Do you see a way to reduce this redundancy?

**Comment by tamird** [comment]
@knz you might be able to move some things into gosigar_unix, or else create a new file that doesn't end in `_GOOS` and use build tags to control when it is built.

**Comment by knz** [comment]
@tamird good idea! I just did this and it works well. Thanks!

**Comment by tamird** [comment]
looks like there's some new interaction with darwin that is failing in travis.

**Comment by knz** [comment]
Ping, any news on this one?

**Comment by monicasarbu** [comment]
@knz thank you for your contribution. I am merging your PR.

**Pull request merged**
