### PR TITLE
Fix the FreeBSD build.

### PR DESCRIPTION
**Pull request by knz**
This follows-up on #33 by adding the missing changes (I had these uncommitted in my working tree, sorry for the inconvenience).

### CODE REVIEW

**Comment by andrewkroh** [comment]
@knz No problem. Thanks for the fix. This highlights our need for better cross-platform testing for the project. I've been wanting to add some CI jobs that test and build PRs on openbsd and freebsd.

**Comment by gregoryo2014** [comment]
@knz From a position of relative ignorance, I'd like to know why it requires the linux compat components of FreeBSD, instead of using FreeBSD native components. Can you shed some light?

**Comment by gregoryo2014** [comment]
Oh, and thank you for making this work! ELK just got a whole lot more useful to us.

**Comment by knz** [comment]
@gregoryo2014 because I was lazy! (jk - just not enough time to dig up all the freebsd native apis. This was done in a rush. It was easier to just reuse most of the linux code and just pad with freebsd native apis when the linux code didn't work.)

**Comment by gregoryo2014** [comment]
Understood, and thank you again for the work. Laziness can be a virtue if applied well to programming.

@knz If I wanted to learn what's necessary to replace some of those Linux calls with FreeBSD calls, could you suggest how I might get started?

**Comment by knz** [comment]
@gregoryo2014 so most of the information that gosigar wants is read on Linux by opening and reading pseudo-files in the /proc filesystem. Most of this code now sits in sigar_linux_common.go. On FreeBSD this information is usually not available via /proc, but instead you have to call specific syscalls (e.g. `getfsstat()` for `FileSystemList`) or the general-purpose `sysctl()` function (eg for `FDUsage`). 

If you are lucky some of the code from the OpenBSD implementation can be used as-is or very little changes on FreeBSD. I can see for example that the code for `FileSystemList` probably is fine to use on FreeBSD too (since FreeBSD also supports `getfsstat()`). However some other code definitely will not work (and need to be rewritten quite differently), especially when it touches area where OpenBSD uses a rather different kernel implementation from FreeBSD, for example for gosigar's `Mem`.

Your best bet for each function is to:

1. check if the OpenBSD code already works or with minor tweaks, then use that
2. use the `apropos` command to search for specific syscalls that may give you the required information. If you find one, use that (see `Uptime` in `sigar_freebsd.go` for an example)
3. use `sysctl -a` on the command line to find sysctl entries that give you what you want. If you find one, use that (see `FDUsage` in `sigar_freebsd.go` for an example)

Note that using  `/compat/linux/proc` like this code now does is not unheard of where it comes to FreeBSD sysadmin tools. For example htop does the same.

**Comment by gregoryo2014** [comment]
@knz Excellent, thank you for that detailed description. I will attempt to work on it as a side project in all of my spare time :P
> Note that using ``/compat/linux/proc`` like this code now does is not unheard of where it comes to FreeBSD sysadmin tools. For example htop does the same.

Yes, I understand it's not a dirty hack, but an implementation decision - you mentioned laziness, which is pretty widely accepted as a positive trait in programmers! I like the idea of not deploying Linux compat to every machine where I want metricbeat (and thus gosigar), so there is motivation for me for this work. Meanwhile, I will deploy it as is where we want it.

**Comment by knz** [comment]
@gregoryo2014 oh wait but are you sure you understand what's going on? This implementation does not require the linux compat packages to be installed at all! It merely requires that the /compat/linux/proc filesystem is mounted, which you can do even when compat-linux is not installed by simply running

   mount -t linprocfs /dev/nulll /compat/linux/proc

**Comment by andrewkroh** [comment]
I added a note about the procfs requirement to the Metricbeat FAQ. https://www.elastic.co/guide/en/beats/metricbeat/current/_how_do_i_fix_the_literal_open_compat_linux_proc_no_such_file_or_directory_literal_error_on_freebsd.html

**Comment by gregoryo2014** [comment]
Ah yes, I see @knz. I mistakenly assumed that it needed the compat packages. So, the payoff for that extra work would be pretty low. Thanks @andrewkroh for the FAQ update.

**Pull request merged**
