### PR TITLE
Add a working implementation of ProcFDUsage for FreeBSD.

### PR DESCRIPTION
**Pull request by knz**
Fixes https://github.com/elastic/gosigar/issues/43.

@andrewkroh can you check this and verify it works on your system?

### CODE REVIEW

**Comment by andrewkroh** [comment]
@knz I found one issue with my setup that was causing the `/proc/<pid>/rlimit` to not be present. I had mounted [`linprocfs`](http://nixdoc.net/man-pages/FreeBSD/man5/linprocfs.5.html) instead of [`procfs`](http://nixdoc.net/man-pages/FreeBSD/man5/procfs.5.html). `linprocfs` does not expose the `rlimit` data.

But I still haven't been able to make `/proc/<pid>/fd` work. It's not mentioned on the procfs manpage. Is this working for you? I tried FreedBSD 10.2 and 11.0-CURRENT. How should I be setting up the procfs filesystem, is it just `sudo mount -t procfs proc /proc`?

**Comment by knz** [comment]
You need both `/proc/<pid>/rlimit` and `/compat/linux/proc/<pid>/fd` separately (that's what my code does).

**Comment by andrewkroh** [comment]
@knz So it looks like only `/compat/linux/proc/self/fd` provides FD usage info. All other processes have "unknown" symlinks listed for `/compat/linux/proc/self/fd`. Is that what you are seeing as well? (Sorry, I'm not much of a FreeBSD user.) Thanks!

That appears to be how the code is implemented in `linprocfs`. http://www.leidinger.net/freebsd/dox/linux/html/d0/d56/linprocfs_8c_source.html#l01357

**Comment by knz** [comment]
Woah I didn't think people would use this gosigar interface to inspect other processes. Peeking into another process' fd list is a priviledged operation and you should be root to do that, right?

**Comment by andrewkroh** [comment]
Yeah, it's a privileged operation that can be done on Linux. That's where I got the expectation that I would be able to do it on FreeBSD.

I have a better understanding of how this works now. I just need to make sure to document the need to mount both linprocfs and procfs.

**Comment by knz** [comment]
Well there must be a way since "lsof" works on FreeBSD too. I don't have time to do this now but that would be the best way to address this. I suspect it uses a library to interface with the process table in kernel memory, like top does. Unfortunately I do not have time to look into this now.

**Pull request merged**
